var searchData=
[
  ['（修改地图原点）_0',['RflyCesiumOriPos(double lat, double lon, double Alt, double SolarTime)（修改地图原点）',['../md_ue_2md_2command_2RflyCesiumOriPos.html',1,'']]],
  ['（修改运行速度）_1',['slomo （修改运行速度）',['../md_ue_2md_2command_2slomo__.html',1,'']]],
  ['（修改copter样式）_2',['RflyChange3DModel(int CopterID, int veTypes=0)（修改Copter样式）',['../md_ue_2md_2command_2RflyChange3DModel.html',1,'']]],
  ['（偏移相机）_3',['RflyCameraPosAngAdd(float x, float y, float z,float roll,float pitch,float yaw)（偏移相机）',['../md_ue_2md_2command_2RflyCameraPosAngAdd.html',1,'']]],
  ['（偏移copter）_4',['RflyMoveVehiclePosAng(int CopterID, int isFitGround, float x, float y, float z, float roll, float pitch, float yaw)（偏移Copter）',['../md_ue_2md_2command_2RflyMoveVehiclePosAng.html',1,'']]],
  ['（全局缩放）_5',['RflySetPosScale(float scale)（全局缩放）',['../md_ue_2md_2command_2RflySetPosScale.html',1,'']]],
  ['（切换传图模式）_6',['RflyEnImgSync(int isEnable)（切换传图模式）',['../md_ue_2md_2command_2RflyEnImgSync.html',1,'']]],
  ['（定义轨迹颜色）_7',['RflySetCopterLine(int CopterID, FString colorStr)（定义轨迹颜色）',['../md_ue_2md_2command_2RflySetCopterLine.html',1,'']]],
  ['（执行txt脚本）_8',['RflyLoad3DFile(FString FileName)（执行TXT脚本）',['../md_ue_2md_2command_2RflyLoad3DFile.html',1,'']]],
  ['（扫描地形）_9',['RflyScanTerrainH(float xLeftBottom(m), float yLeftBottom(m), float xRightTop(m), float yRightTop(m), float scanHeight(m), float scanInterval(m))（扫描地形）',['../md_ue_2md_2command_2RflyScanTerrainH.html',1,'']]],
  ['（拒收指定copter数据）_10',['RflyDisableVeMove(FString CopterIDList, int disable)（拒收指定Copter数据）',['../md_ue_2md_2command_2RflyDisableVeMove.html',1,'']]],
  ['（指定回传数据）_11',['RflyReqObjData(int opFlag, FString objName, FString colorStr)（指定回传数据）',['../md_ue_2md_2command_2RflyReqObjData.html',1,'']]],
  ['（显示文本）_12',['RflyShowTextTime(String txt, float time)（显示文本）',['../md_ue_2md_2command_2RflyShowTextTime.html',1,'']]],
  ['（根据名称切换地图）_13',['RflyChangeMapbyName(String txt)（根据名称切换地图）',['../md_ue_2md_2command_2RflyChangeMapbyName.html',1,'']]],
  ['（根据id切换地图）_14',['RflyChangeMapbyID(int id)（根据ID切换地图）',['../md_ue_2md_2command_2RflyChangeMapbyID.html',1,'']]],
  ['（模拟快捷键）_15',['RflyChangeViewKeyCmd(String key, int num)（模拟快捷键）',['../md_ue_2md_2command_2RflyChangeViewKeyCmd.html',1,'']]],
  ['（清空图像缓存）_16',['RflyClearCapture(int seqID)（清空图像缓存）',['../md_ue_2md_2command_2RflyClearCapture.html',1,'']]],
  ['（清除copter）_17',['RflyDelVehicles(FString CopterIDList)（清除Copter）',['../md_ue_2md_2command_2RflyDelVehicles.html',1,'']]],
  ['（激活数据回传）_18',['RflyReqVehicleData(FString isEnable)（激活数据回传）',['../md_ue_2md_2command_2RflyReqVehicleData.html',1,'']]],
  ['（生成_20ref_20_5fclassid（模型类别id）_20classid_20为“_20”的物体）：_19',['O+数字*（生成@ref &quot;_ClassID（模型类别ID）&quot; &quot;ClassID&quot;为“*”的物体）：',['../md_ue_2md_2key_2O.html',1,'']]],
  ['（触发扩展蓝图接口，该功能仅限个人高级版以上）_20',['RflySetActuatorPWMsExt(int CopterID, float pwm9, float pwm10, float pwm11, float pwm12, float pwm13, float pwm14, float pwm15, float pwm16, float pwm17, float pwm18, float pwm19, float pwm20, float pwm21, float pwm22, float pwm23, float pwm24)（触发扩展蓝图接口，该功能仅限个人高级版以上）',['../md_ue_2md_2command_2RflySetActuatorPWMsExt.html',1,'']]],
  ['（触发蓝图接口，该功能仅限个人高级版以上）_21',['RflySetActuatorPWMs(int CopterID, float pwm1, float pwm2, float pwm3, float pwm4, float pwm5, float pwm6, float pwm7, float pwm8)（触发蓝图接口，该功能仅限个人高级版以上）',['../md_ue_2md_2command_2RflySetActuatorPWMs.html',1,'']]],
  ['（设置视域）_22',['RflyCameraFovDegrees(float degrees)（设置视域）',['../md_ue_2md_2command_2RflyCameraFovDegrees.html',1,'']]],
  ['（设置copterid标签下方显示）_23',['RflySetMsgLabel(int CopterID, FString Text, FString colorStr, float size, float time, int flag)（设置CopterID标签下方显示）',['../md_ue_2md_2command_2RflySetMsgLabel.html',1,'']]],
  ['（设置copterid标签处显示）_24',['RflySetIDLabel(int CopterID,FString Text, FString colorStr, float size)（设置CopterID标签处显示）',['../md_ue_2md_2command_2RflySetIDLabel.html',1,'']]],
  ['（调整copter尺寸）_25',['RflyChangeVehicleSize(int CopterID, float size=0)（调整Copter尺寸）',['../md_ue_2md_2command_2RflyChangeVehicleSize.html',1,'']]],
  ['（重设相机）_26',['RflyCameraPosAng(float x, float y, float z, float roll, float pitch, float yaw)（重设相机）',['../md_ue_2md_2command_2RflyCameraPosAng.html',1,'']]],
  ['（重设copter）_27',['RflySetVehiclePosAng(int CopterID, int isFitGround, float x, float y, float z, float roll,float pitch, float yaw)（重设Copter）',['../md_ue_2md_2command_2RflySetVehiclePosAng.html',1,'']]]
];
