var searchData=
[
  ['r_20forcelod（lod点面数）_0',['r.ForceLOD（LOD点面数）',['../md_ue_2md_2command_2r_8ForceLOD.html',1,'']]],
  ['r_20mipmaplodbias（纹理层级偏差）_1',['r.MipMapLODBias（纹理层级偏差）',['../md_ue_2md_2command_2r_8MipMapLODBias.html',1,'']]],
  ['r_20postprocessaaquality（抗锯齿质量）_2',['r.PostProcessAAQuality（抗锯齿质量）',['../md_ue_2md_2command_2r_8PostProcessAAQuality.html',1,'']]],
  ['r_20screenpercentage（渲染分辨率百分比）_3',['r.ScreenPercentage（渲染分辨率百分比）',['../md_ue_2md_2command_2r_8ScreenPercentage.html',1,'']]],
  ['r_20setnearclipplane（视口近裁剪面）_4',['r.SetNearClipPlane（视口近裁剪面）',['../md_ue_2md_2command_2r_8SetNearClipPlane.html',1,'']]],
  ['r_20setres（设置显示分辨率）_5',['r.setRes（设置显示分辨率）',['../md_ue_2md_2command_2r_8setRes.html',1,'']]],
  ['r_20shadowquality（阴影质量）_6',['r.ShadowQuality（阴影质量）',['../md_ue_2md_2command_2r_8ShadowQuality.html',1,'']]],
  ['r_20streaming_20poolsize_7',['r.Streaming.PoolSize',['../md_ue_2md_2command_2r_8Streaming_8PoolSize.html',1,'']]],
  ['rcoverctrlapi—遥控器手动控制信号的覆盖模块_8',['RCOverCtrlAPI—遥控器手动控制信号的覆盖模块',['../md_ctrl_2md_2RCOverCtrlAPI.html',1,'']]],
  ['read_20adc_20channels—输出外部adc的输入_9',['Read ADC Channels—输出外部ADC的输入',['../md_ctrl_2md_2Read_01ADC_01Channels.html',1,'']]],
  ['read_20and_20write_10',['uORB Read and Write',['../md_ctrl_2md_2uORB_01Read_01and_01Write.html',1,'']]],
  ['read_20async—获取与uorb_20topic相关的数据_11',['uORB Read Async—获取与uORB Topic相关的数据',['../md_ctrl_2md_2uORB_01Read_01Async.html',1,'']]],
  ['read_20function_20call_20trigger—uorb消息读取回调函数触发模块_12',['uORB Read Function-Call Trigger—uORB消息读取回调函数触发模块',['../md_ctrl_2md_2uORB_01Read_01Function-Call_01Trigger.html',1,'']]],
  ['real_5fdata_5fdecoder——解码模块_13',['real_data_decoder——解码模块',['../md_swarm_2md_2real__data__decoder.html',1,'']]],
  ['realctrl28d——控制接口_14',['RealCtrl28D——控制接口',['../md_swarm_2md_2RealCtrl28D.html',1,'']]],
  ['ref_20_5fclassid（模型类别id）_20classid_20为“_20”的物体）：_15',['O+数字*（生成@ref &quot;_ClassID（模型类别ID）&quot; &quot;ClassID&quot;为“*”的物体）：',['../md_ue_2md_2key_2O.html',1,'']]],
  ['repx4block—在线屏蔽px4输出模块_16',['RePX4Block—在线屏蔽PX4输出模块',['../md_ctrl_2md_2RePX4Block.html',1,'']]],
  ['rflycamerafovdegrees_20float_20degrees_20（设置视域）_17',['RflyCameraFovDegrees(float degrees)（设置视域）',['../md_ue_2md_2command_2RflyCameraFovDegrees.html',1,'']]],
  ['rflycameraposang_20float_20x_20float_20y_20float_20z_20float_20roll_20float_20pitch_20float_20yaw_20（重设相机）_18',['RflyCameraPosAng(float x, float y, float z, float roll, float pitch, float yaw)（重设相机）',['../md_ue_2md_2command_2RflyCameraPosAng.html',1,'']]],
  ['rflycameraposangadd_20float_20x_20float_20y_20float_20z_20float_20roll_20float_20pitch_20float_20yaw_20（偏移相机）_19',['RflyCameraPosAngAdd(float x, float y, float z,float roll,float pitch,float yaw)（偏移相机）',['../md_ue_2md_2command_2RflyCameraPosAngAdd.html',1,'']]],
  ['rflycesiumoripos_20double_20lat_20double_20lon_20double_20alt_20double_20solartime_20（修改地图原点）_20',['RflyCesiumOriPos(double lat, double lon, double Alt, double SolarTime)（修改地图原点）',['../md_ue_2md_2command_2RflyCesiumOriPos.html',1,'']]],
  ['rflychange3dmodel_20int_20copterid_20int_20vetypes_200_20（修改copter样式）_21',['RflyChange3DModel(int CopterID, int veTypes=0)（修改Copter样式）',['../md_ue_2md_2command_2RflyChange3DModel.html',1,'']]],
  ['rflychangemapbyid_20int_20id_20（根据id切换地图）_22',['RflyChangeMapbyID(int id)（根据ID切换地图）',['../md_ue_2md_2command_2RflyChangeMapbyID.html',1,'']]],
  ['rflychangemapbyname_20string_20txt_20（根据名称切换地图）_23',['RflyChangeMapbyName(String txt)（根据名称切换地图）',['../md_ue_2md_2command_2RflyChangeMapbyName.html',1,'']]],
  ['rflychangevehiclesize_20int_20copterid_20float_20size_200_20（调整copter尺寸）_24',['RflyChangeVehicleSize(int CopterID, float size=0)（调整Copter尺寸）',['../md_ue_2md_2command_2RflyChangeVehicleSize.html',1,'']]],
  ['rflychangeviewkeycmd_20string_20key_20int_20num_20（模拟快捷键）_25',['RflyChangeViewKeyCmd(String key, int num)（模拟快捷键）',['../md_ue_2md_2command_2RflyChangeViewKeyCmd.html',1,'']]],
  ['rflyclearcapture_20int_20seqid_20（清空图像缓存）_26',['RflyClearCapture(int seqID)（清空图像缓存）',['../md_ue_2md_2command_2RflyClearCapture.html',1,'']]],
  ['rflydelvehicles_20fstring_20copteridlist_20（清除copter）_27',['RflyDelVehicles(FString CopterIDList)（清除Copter）',['../md_ue_2md_2command_2RflyDelVehicles.html',1,'']]],
  ['rflydisablevemove_20fstring_20copteridlist_20int_20disable_20（拒收指定copter数据）_28',['RflyDisableVeMove(FString CopterIDList, int disable)（拒收指定Copter数据）',['../md_ue_2md_2command_2RflyDisableVeMove.html',1,'']]],
  ['rflyenimgsync_20int_20isenable_20（切换传图模式）_29',['RflyEnImgSync(int isEnable)（切换传图模式）',['../md_ue_2md_2command_2RflyEnImgSync.html',1,'']]],
  ['rflyload3dfile_20fstring_20filename_20（执行txt脚本）_30',['RflyLoad3DFile(FString FileName)（执行TXT脚本）',['../md_ue_2md_2command_2RflyLoad3DFile.html',1,'']]],
  ['rflymovevehicleposang_20int_20copterid_20int_20isfitground_20float_20x_20float_20y_20float_20z_20float_20roll_20float_20pitch_20float_20yaw_20（偏移copter）_31',['RflyMoveVehiclePosAng(int CopterID, int isFitGround, float x, float y, float z, float roll, float pitch, float yaw)（偏移Copter）',['../md_ue_2md_2command_2RflyMoveVehiclePosAng.html',1,'']]],
  ['rflyreqobjdata_20int_20opflag_20fstring_20objname_20fstring_20colorstr_20（指定回传数据）_32',['RflyReqObjData(int opFlag, FString objName, FString colorStr)（指定回传数据）',['../md_ue_2md_2command_2RflyReqObjData.html',1,'']]],
  ['rflyreqvehicledata_20fstring_20isenable_20（激活数据回传）_33',['RflyReqVehicleData(FString isEnable)（激活数据回传）',['../md_ue_2md_2command_2RflyReqVehicleData.html',1,'']]],
  ['rflyscanterrainh_20float_20xleftbottom_20m_20float_20yleftbottom_20m_20float_20xrighttop_20m_20float_20yrighttop_20m_20float_20scanheight_20m_20float_20scaninterval_20m_20（扫描地形）_34',['RflyScanTerrainH(float xLeftBottom(m), float yLeftBottom(m), float xRightTop(m), float yRightTop(m), float scanHeight(m), float scanInterval(m))（扫描地形）',['../md_ue_2md_2command_2RflyScanTerrainH.html',1,'']]],
  ['rflysdk项目主页_35',['RflySDK项目主页',['../index.html',1,'']]],
  ['rflyserialraw——通信模块_36',['RflySerialRaw——通信模块',['../md_swarm_2md_2RflySerialRaw.html',1,'']]],
  ['rflysetactuatorpwms_20int_20copterid_20float_20pwm1_20float_20pwm2_20float_20pwm3_20float_20pwm4_20float_20pwm5_20float_20pwm6_20float_20pwm7_20float_20pwm8_20（触发蓝图接口，该功能仅限个人高级版以上）_37',['RflySetActuatorPWMs(int CopterID, float pwm1, float pwm2, float pwm3, float pwm4, float pwm5, float pwm6, float pwm7, float pwm8)（触发蓝图接口，该功能仅限个人高级版以上）',['../md_ue_2md_2command_2RflySetActuatorPWMs.html',1,'']]],
  ['rflysetactuatorpwmsext_20int_20copterid_20float_20pwm9_20float_20pwm10_20float_20pwm11_20float_20pwm12_20float_20pwm13_20float_20pwm14_20float_20pwm15_20float_20pwm16_20float_20pwm17_20float_20pwm18_20float_20pwm19_20float_20pwm20_20float_20pwm21_20float_20pwm22_20float_20pwm23_20float_20pwm24_20（触发扩展蓝图接口，该功能仅限个人高级版以上）_38',['RflySetActuatorPWMsExt(int CopterID, float pwm9, float pwm10, float pwm11, float pwm12, float pwm13, float pwm14, float pwm15, float pwm16, float pwm17, float pwm18, float pwm19, float pwm20, float pwm21, float pwm22, float pwm23, float pwm24)（触发扩展蓝图接口，该功能仅限个人高级版以上）',['../md_ue_2md_2command_2RflySetActuatorPWMsExt.html',1,'']]],
  ['rflysetcopterline_20int_20copterid_20fstring_20colorstr_20（定义轨迹颜色）_39',['RflySetCopterLine(int CopterID, FString colorStr)（定义轨迹颜色）',['../md_ue_2md_2command_2RflySetCopterLine.html',1,'']]],
  ['rflysetidlabel_20int_20copterid_20fstring_20text_20fstring_20colorstr_20float_20size_20（设置copterid标签处显示）_40',['RflySetIDLabel(int CopterID,FString Text, FString colorStr, float size)（设置CopterID标签处显示）',['../md_ue_2md_2command_2RflySetIDLabel.html',1,'']]],
  ['rflysetmsglabel_20int_20copterid_20fstring_20text_20fstring_20colorstr_20float_20size_20float_20time_20int_20flag_20（设置copterid标签下方显示）_41',['RflySetMsgLabel(int CopterID, FString Text, FString colorStr, float size, float time, int flag)（设置CopterID标签下方显示）',['../md_ue_2md_2command_2RflySetMsgLabel.html',1,'']]],
  ['rflysetposscale_20float_20scale_20（全局缩放）_42',['RflySetPosScale(float scale)（全局缩放）',['../md_ue_2md_2command_2RflySetPosScale.html',1,'']]],
  ['rflysetvehicleposang_20int_20copterid_20int_20isfitground_20float_20x_20float_20y_20float_20z_20float_20roll_20float_20pitch_20float_20yaw_20（重设copter）_43',['RflySetVehiclePosAng(int CopterID, int isFitGround, float x, float y, float z, float roll,float pitch, float yaw)（重设Copter）',['../md_ue_2md_2command_2RflySetVehiclePosAng.html',1,'']]],
  ['rflyshowtexttime_20string_20txt_20float_20time_20（显示文本）_44',['RflyShowTextTime(String txt, float time)（显示文本）',['../md_ue_2md_2command_2RflyShowTextTime.html',1,'']]],
  ['rflysim_20apis_45',['RflySim APIs',['../md_ctrl_2md_2RflySim_01APIs.html',1,'']]],
  ['rflysim_20model_46',['RflySim Model',['../md_ctrl_2md_2RflySim_01Model.html',1,'']]],
  ['rflysim_20phm_47',['RflySim phm',['../md_phm_2md_2PHMmodels.html',1,'']]],
  ['rflysim_20swarm_48',['RflySim Swarm',['../md_swarm_2md_2SwarmAPIs.html',1,'']]],
  ['rflysim3d场景所需文件_49',['RflySim3D场景所需文件',['../md_ue_2md_2Terrain.html',1,'']]],
  ['rflyudpfast——通信模块_50',['RflyUdpFast——通信模块',['../md_swarm_2md_2RflyUdpFast.html',1,'']]],
  ['rflyudpmavlink——通信模块_51',['RflyUdpMavlink——通信模块',['../md_swarm_2md_2RflyUdpMavlink.html',1,'']]],
  ['rflyudpraw——通信模块_52',['RflyUdpRaw——通信模块',['../md_swarm_2md_2RflyUdpRaw.html',1,'']]],
  ['rflyvrpnrecv——通信模块_53',['RflyVrpnRecv——通信模块',['../md_swarm_2md_2RflyVrpnRecv.html',1,'']]],
  ['rgb_5fled—led灯_54',['RGB_LED—LED灯',['../md_ctrl_2md_2RGB__LED.html',1,'']]],
  ['rhi（显示gpu上的消耗细则）_55',['stat rhi（显示GPU上的消耗细则）',['../md_ue_2md_2command_2stat__rhi.html',1,'']]],
  ['roll_20float_20pitch_20float_20yaw_20（偏移相机）_56',['RflyCameraPosAngAdd(float x, float y, float z,float roll,float pitch,float yaw)（偏移相机）',['../md_ue_2md_2command_2RflyCameraPosAngAdd.html',1,'']]],
  ['roll_20float_20pitch_20float_20yaw_20（偏移copter）_57',['RflyMoveVehiclePosAng(int CopterID, int isFitGround, float x, float y, float z, float roll, float pitch, float yaw)（偏移Copter）',['../md_ue_2md_2command_2RflyMoveVehiclePosAng.html',1,'']]],
  ['roll_20float_20pitch_20float_20yaw_20（重设相机）_58',['RflyCameraPosAng(float x, float y, float z, float roll, float pitch, float yaw)（重设相机）',['../md_ue_2md_2command_2RflyCameraPosAng.html',1,'']]],
  ['roll_20float_20pitch_20float_20yaw_20（重设copter）_59',['RflySetVehiclePosAng(int CopterID, int isFitGround, float x, float y, float z, float roll,float pitch, float yaw)（重设Copter）',['../md_ue_2md_2command_2RflySetVehiclePosAng.html',1,'']]]
];
